### PR TITLE
InspectAssembly Code Reorg

### PR DESCRIPTION
**Pull request by djhohnstein**
I made it better.

### CODE REVIEW

**Comment by matterpreter** [comment]
@djhohnstein This is great! I merged prematurely and found some issues, so opening this back up.

1. The TypeFilterLevel stuff only applies to `BinaryFormatter`, so including it with others doesn't make sense
2. WCF stuff is included in serialization gadgets
3. The "all pids" check is failing to detect all running .NET assemblies

**Comment by matterpreter** [comment]
GitHub won't let me reopen a merged PR. Can you open a new one?

**Comment by djhohnstein** [comment]
Yeah I'll reopen when I get the chance 👍

**Comment by djhohnstein** [comment]
Could you upload example assemblies that aren't getting caught as well for me to diagnose?

**Pull request merged**
